# frozen_string_literal: true

source "https://rubygems.org"
gem "jekyll"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem "github-pages"
group :jekyll_plugins do
	gem 'jekyll-sitemap'
	gem 'jekyll-feed'
	gem 'jekyll-seo-tag'
	gem 'github-pages'
end

# gem "rails"

gem "webrick", "~> 1.7"
